-- Add visa requirements data for Canadian passport holders
INSERT INTO visa_requirements (passport_country, destination_country, status, allowed_stay_days, visa_fee_amount, visa_fee_currency, notes) VALUES
-- North America
('CA', 'US', 'visa_free', 180, 0, 'USD', 'No visa required for tourism'),
('CA', 'MX', 'visa_free', 180, 0, 'USD', 'No visa required for tourism'),

-- Europe
('CA', 'GB', 'visa_free', 180, 0, 'GBP', 'No visa required for tourism'),
('CA', 'FR', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'DE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'IT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'ES', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'NL', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'BE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'AT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'CH', 'visa_free', 90, 0, 'CHF', 'No visa required for tourism'),
('CA', 'SE', 'visa_free', 90, 0, 'SEK', 'No visa required for tourism'),
('CA', 'NO', 'visa_free', 90, 0, 'NOK', 'No visa required for tourism'),
('CA', 'DK', 'visa_free', 90, 0, 'DKK', 'No visa required for tourism'),
('CA', 'FI', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'PT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'IE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'GR', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'PL', 'visa_free', 90, 0, 'PLN', 'No visa required for tourism'),
('CA', 'CZ', 'visa_free', 90, 0, 'CZK', 'No visa required for tourism'),
('CA', 'HU', 'visa_free', 90, 0, 'HUF', 'No visa required for tourism'),
('CA', 'SK', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'SI', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'EE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'LV', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'LT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'HR', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'BG', 'visa_free', 90, 0, 'BGN', 'No visa required for tourism'),
('CA', 'RO', 'visa_free', 90, 0, 'RON', 'No visa required for tourism'),
('CA', 'CY', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'MT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'LU', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),

-- Asia Pacific
('CA', 'JP', 'visa_free', 90, 0, 'JPY', 'No visa required for tourism'),
('CA', 'KR', 'visa_free', 180, 0, 'KRW', 'No visa required for tourism'),
('CA', 'SG', 'visa_free', 30, 0, 'SGD', 'No visa required for tourism'),
('CA', 'MY', 'visa_free', 90, 0, 'MYR', 'No visa required for tourism'),
('CA', 'TH', 'visa_free', 30, 0, 'THB', 'No visa required for tourism'),
('CA', 'PH', 'visa_free', 30, 0, 'PHP', 'No visa required for tourism'),
('CA', 'ID', 'visa_free', 30, 0, 'IDR', 'No visa required for tourism'),
('CA', 'VN', 'visa_free', 15, 0, 'VND', 'No visa required for tourism'),
('CA', 'KH', 'visa_free', 30, 0, 'USD', 'No visa required for tourism'),
('CA', 'LA', 'visa_free', 30, 0, 'USD', 'No visa required for tourism'),
('CA', 'MM', 'visa_free', 28, 0, 'USD', 'No visa required for tourism'),
('CA', 'BN', 'visa_free', 14, 0, 'BND', 'No visa required for tourism'),
('CA', 'TL', 'visa_free', 30, 0, 'USD', 'No visa required for tourism'),

-- Oceania
('CA', 'AU', 'eta_required', 90, 20, 'AUD', 'Electronic Travel Authorization required'),
('CA', 'NZ', 'visa_free', 90, 0, 'NZD', 'No visa required for tourism'),
('CA', 'FJ', 'visa_free', 120, 0, 'FJD', 'No visa required for tourism'),
('CA', 'PG', 'visa_free', 60, 0, 'PGK', 'No visa required for tourism'),
('CA', 'VU', 'visa_free', 30, 0, 'VUV', 'No visa required for tourism'),
('CA', 'NC', 'visa_free', 90, 0, 'XPF', 'No visa required for tourism'),
('CA', 'PF', 'visa_free', 90, 0, 'XPF', 'No visa required for tourism'),

-- South America
('CA', 'BR', 'visa_free', 90, 0, 'BRL', 'No visa required for tourism'),
('CA', 'AR', 'visa_free', 90, 0, 'ARS', 'No visa required for tourism'),
('CA', 'CL', 'visa_free', 90, 0, 'CLP', 'No visa required for tourism'),
('CA', 'PE', 'visa_free', 183, 0, 'PEN', 'No visa required for tourism'),
('CA', 'CO', 'visa_free', 90, 0, 'COP', 'No visa required for tourism'),
('CA', 'EC', 'visa_free', 90, 0, 'USD', 'No visa required for tourism'),
('CA', 'UY', 'visa_free', 90, 0, 'UYU', 'No visa required for tourism'),
('CA', 'PY', 'visa_free', 90, 0, 'PYG', 'No visa required for tourism'),
('CA', 'BO', 'visa_free', 90, 0, 'BOB', 'No visa required for tourism'),
('CA', 'GY', 'visa_free', 90, 0, 'GYD', 'No visa required for tourism'),
('CA', 'SR', 'visa_free', 90, 0, 'SRD', 'No visa required for tourism'),
('CA', 'GF', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),

-- Africa
('CA', 'ZA', 'visa_free', 90, 0, 'ZAR', 'No visa required for tourism'),
('CA', 'NA', 'visa_free', 90, 0, 'NAD', 'No visa required for tourism'),
('CA', 'BW', 'visa_free', 90, 0, 'BWP', 'No visa required for tourism'),
('CA', 'ZW', 'visa_free', 90, 0, 'USD', 'No visa required for tourism'),
('CA', 'ZM', 'visa_free', 90, 0, 'ZMW', 'No visa required for tourism'),
('CA', 'MW', 'visa_free', 90, 0, 'MWK', 'No visa required for tourism'),
('CA', 'TZ', 'visa_free', 90, 0, 'TZS', 'No visa required for tourism'),
('CA', 'KE', 'visa_free', 90, 0, 'KES', 'No visa required for tourism'),
('CA', 'UG', 'visa_free', 90, 0, 'UGX', 'No visa required for tourism'),
('CA', 'RW', 'visa_free', 90, 0, 'RWF', 'No visa required for tourism'),
('CA', 'BI', 'visa_free', 30, 0, 'BIF', 'No visa required for tourism'),
('CA', 'ET', 'visa_free', 90, 0, 'ETB', 'No visa required for tourism'),
('CA', 'ER', 'visa_free', 90, 0, 'ERN', 'No visa required for tourism'),
('CA', 'DJ', 'visa_free', 90, 0, 'DJF', 'No visa required for tourism'),
('CA', 'SO', 'visa_free', 30, 0, 'SOS', 'No visa required for tourism'),
('CA', 'SS', 'visa_free', 90, 0, 'SSP', 'No visa required for tourism'),
('CA', 'SD', 'visa_free', 90, 0, 'SDG', 'No visa required for tourism'),
('CA', 'EG', 'visa_free', 90, 0, 'EGP', 'No visa required for tourism'),
('CA', 'LY', 'visa_free', 90, 0, 'LYD', 'No visa required for tourism'),
('CA', 'TN', 'visa_free', 90, 0, 'TND', 'No visa required for tourism'),
('CA', 'DZ', 'visa_free', 90, 0, 'DZD', 'No visa required for tourism'),
('CA', 'MA', 'visa_free', 90, 0, 'MAD', 'No visa required for tourism'),
('CA', 'SN', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('CA', 'GN', 'visa_free', 90, 0, 'GNF', 'No visa required for tourism'),
('CA', 'SL', 'visa_free', 90, 0, 'SLL', 'No visa required for tourism'),
('CA', 'LR', 'visa_free', 90, 0, 'LRD', 'No visa required for tourism'),
('CA', 'CI', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('CA', 'GH', 'visa_free', 90, 0, 'GHS', 'No visa required for tourism'),
('CA', 'TG', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('CA', 'BJ', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('CA', 'NG', 'visa_free', 90, 0, 'NGN', 'No visa required for tourism'),
('CA', 'CM', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('CA', 'TD', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('CA', 'CF', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('CA', 'CG', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('CA', 'CD', 'visa_free', 90, 0, 'CDF', 'No visa required for tourism'),
('CA', 'GA', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('CA', 'GQ', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('CA', 'ST', 'visa_free', 90, 0, 'STN', 'No visa required for tourism'),
('CA', 'AO', 'visa_free', 90, 0, 'AOA', 'No visa required for tourism'),
('CA', 'MZ', 'visa_free', 90, 0, 'MZN', 'No visa required for tourism'),
('CA', 'MG', 'visa_free', 90, 0, 'MGA', 'No visa required for tourism'),
('CA', 'MU', 'visa_free', 90, 0, 'MUR', 'No visa required for tourism'),
('CA', 'SC', 'visa_free', 90, 0, 'SCR', 'No visa required for tourism'),
('CA', 'KM', 'visa_free', 90, 0, 'KMF', 'No visa required for tourism'),
('CA', 'YT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('CA', 'RE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),

-- Middle East
('CA', 'IL', 'visa_free', 90, 0, 'ILS', 'No visa required for tourism'),
('CA', 'JO', 'visa_free', 90, 0, 'JOD', 'No visa required for tourism'),
('CA', 'LB', 'visa_free', 90, 0, 'LBP', 'No visa required for tourism'),
('CA', 'AE', 'visa_free', 90, 0, 'AED', 'No visa required for tourism'),
('CA', 'BH', 'visa_free', 90, 0, 'BHD', 'No visa required for tourism'),
('CA', 'KW', 'visa_free', 90, 0, 'KWD', 'No visa required for tourism'),
('CA', 'QA', 'visa_free', 90, 0, 'QAR', 'No visa required for tourism'),
('CA', 'OM', 'visa_free', 90, 0, 'OMR', 'No visa required for tourism'),
('CA', 'YE', 'visa_free', 90, 0, 'YER', 'No visa required for tourism'),

-- Countries requiring visas for Canadians
('CA', 'IN', 'evisa', 60, 25, 'USD', 'Electronic visa required'),
('CA', 'PK', 'consulate_visa', 30, 60, 'USD', 'Visa must be obtained at consulate'),
('CA', 'BD', 'consulate_visa', 30, 50, 'USD', 'Visa must be obtained at consulate'),
('CA', 'LK', 'visa_on_arrival', 30, 35, 'USD', 'Visa on arrival available'),
('CA', 'NP', 'visa_on_arrival', 90, 30, 'USD', 'Visa on arrival available'),
('CA', 'MV', 'visa_on_arrival', 30, 0, 'USD', 'Visa on arrival available'),
('CA', 'TR', 'evisa', 90, 50, 'USD', 'Electronic visa required'),
('CA', 'GE', 'visa_free', 365, 0, 'GEL', 'No visa required for tourism'),
('CA', 'AM', 'visa_free', 180, 0, 'AMD', 'No visa required for tourism'),
('CA', 'AZ', 'visa_free', 30, 0, 'AZN', 'No visa required for tourism'),
('CA', 'KZ', 'visa_free', 30, 0, 'KZT', 'No visa required for tourism'),
('CA', 'KG', 'visa_free', 60, 0, 'KGS', 'No visa required for tourism'),
('CA', 'TJ', 'visa_free', 45, 0, 'TJS', 'No visa required for tourism'),
('CA', 'UZ', 'visa_free', 30, 0, 'UZS', 'No visa required for tourism'),
('CA', 'TM', 'visa_free', 30, 0, 'TMT', 'No visa required for tourism'),
('CA', 'AF', 'consulate_visa', 30, 80, 'USD', 'Visa must be obtained at consulate'),
('CA', 'IR', 'consulate_visa', 30, 80, 'USD', 'Visa must be obtained at consulate'),
('CA', 'IQ', 'consulate_visa', 30, 60, 'USD', 'Visa must be obtained at consulate'),
('CA', 'SY', 'consulate_visa', 30, 50, 'USD', 'Visa must be obtained at consulate'),
('CA', 'SA', 'consulate_visa', 90, 160, 'USD', 'Visa must be obtained at consulate')

ON CONFLICT (passport_country, destination_country) DO NOTHING;

-- Add visa requirements data for Mexican passport holders
INSERT INTO visa_requirements (passport_country, destination_country, status, allowed_stay_days, visa_fee_amount, visa_fee_currency, notes) VALUES
-- North America
('MX', 'US', 'consulate_visa', 180, 160, 'USD', 'Visa must be obtained at consulate'),
('MX', 'CA', 'visa_free', 180, 0, 'CAD', 'No visa required for tourism'),

-- Europe
('MX', 'GB', 'visa_free', 180, 0, 'GBP', 'No visa required for tourism'),
('MX', 'FR', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'DE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'IT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'ES', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'NL', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'BE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'AT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'CH', 'visa_free', 90, 0, 'CHF', 'No visa required for tourism'),
('MX', 'SE', 'visa_free', 90, 0, 'SEK', 'No visa required for tourism'),
('MX', 'NO', 'visa_free', 90, 0, 'NOK', 'No visa required for tourism'),
('MX', 'DK', 'visa_free', 90, 0, 'DKK', 'No visa required for tourism'),
('MX', 'FI', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'PT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'IE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'GR', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'PL', 'visa_free', 90, 0, 'PLN', 'No visa required for tourism'),
('MX', 'CZ', 'visa_free', 90, 0, 'CZK', 'No visa required for tourism'),
('MX', 'HU', 'visa_free', 90, 0, 'HUF', 'No visa required for tourism'),
('MX', 'SK', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'SI', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'EE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'LV', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'LT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'HR', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'BG', 'visa_free', 90, 0, 'BGN', 'No visa required for tourism'),
('MX', 'RO', 'visa_free', 90, 0, 'RON', 'No visa required for tourism'),
('MX', 'CY', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'MT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'LU', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),

-- Asia Pacific
('MX', 'JP', 'visa_free', 180, 0, 'JPY', 'No visa required for tourism'),
('MX', 'KR', 'visa_free', 180, 0, 'KRW', 'No visa required for tourism'),
('MX', 'SG', 'visa_free', 30, 0, 'SGD', 'No visa required for tourism'),
('MX', 'MY', 'visa_free', 90, 0, 'MYR', 'No visa required for tourism'),
('MX', 'TH', 'visa_free', 30, 0, 'THB', 'No visa required for tourism'),
('MX', 'PH', 'visa_free', 30, 0, 'PHP', 'No visa required for tourism'),
('MX', 'ID', 'visa_free', 30, 0, 'IDR', 'No visa required for tourism'),
('MX', 'VN', 'visa_free', 15, 0, 'VND', 'No visa required for tourism'),
('MX', 'KH', 'visa_free', 30, 0, 'USD', 'No visa required for tourism'),
('MX', 'LA', 'visa_free', 30, 0, 'USD', 'No visa required for tourism'),
('MX', 'MM', 'visa_free', 28, 0, 'USD', 'No visa required for tourism'),
('MX', 'BN', 'visa_free', 14, 0, 'BND', 'No visa required for tourism'),
('MX', 'TL', 'visa_free', 30, 0, 'USD', 'No visa required for tourism'),

-- Oceania
('MX', 'AU', 'eta_required', 90, 20, 'AUD', 'Electronic Travel Authorization required'),
('MX', 'NZ', 'visa_free', 90, 0, 'NZD', 'No visa required for tourism'),
('MX', 'FJ', 'visa_free', 120, 0, 'FJD', 'No visa required for tourism'),
('MX', 'PG', 'visa_free', 60, 0, 'PGK', 'No visa required for tourism'),
('MX', 'VU', 'visa_free', 30, 0, 'VUV', 'No visa required for tourism'),
('MX', 'NC', 'visa_free', 90, 0, 'XPF', 'No visa required for tourism'),
('MX', 'PF', 'visa_free', 90, 0, 'XPF', 'No visa required for tourism'),

-- South America
('MX', 'BR', 'visa_free', 90, 0, 'BRL', 'No visa required for tourism'),
('MX', 'AR', 'visa_free', 90, 0, 'ARS', 'No visa required for tourism'),
('MX', 'CL', 'visa_free', 90, 0, 'CLP', 'No visa required for tourism'),
('MX', 'PE', 'visa_free', 183, 0, 'PEN', 'No visa required for tourism'),
('MX', 'CO', 'visa_free', 90, 0, 'COP', 'No visa required for tourism'),
('MX', 'EC', 'visa_free', 90, 0, 'USD', 'No visa required for tourism'),
('MX', 'UY', 'visa_free', 90, 0, 'UYU', 'No visa required for tourism'),
('MX', 'PY', 'visa_free', 90, 0, 'PYG', 'No visa required for tourism'),
('MX', 'BO', 'visa_free', 90, 0, 'BOB', 'No visa required for tourism'),
('MX', 'GY', 'visa_free', 90, 0, 'GYD', 'No visa required for tourism'),
('MX', 'SR', 'visa_free', 90, 0, 'SRD', 'No visa required for tourism'),
('MX', 'GF', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),

-- Africa
('MX', 'ZA', 'visa_free', 90, 0, 'ZAR', 'No visa required for tourism'),
('MX', 'NA', 'visa_free', 90, 0, 'NAD', 'No visa required for tourism'),
('MX', 'BW', 'visa_free', 90, 0, 'BWP', 'No visa required for tourism'),
('MX', 'ZW', 'visa_free', 90, 0, 'USD', 'No visa required for tourism'),
('MX', 'ZM', 'visa_free', 90, 0, 'ZMW', 'No visa required for tourism'),
('MX', 'MW', 'visa_free', 90, 0, 'MWK', 'No visa required for tourism'),
('MX', 'TZ', 'visa_free', 90, 0, 'TZS', 'No visa required for tourism'),
('MX', 'KE', 'visa_free', 90, 0, 'KES', 'No visa required for tourism'),
('MX', 'UG', 'visa_free', 90, 0, 'UGX', 'No visa required for tourism'),
('MX', 'RW', 'visa_free', 90, 0, 'RWF', 'No visa required for tourism'),
('MX', 'BI', 'visa_free', 30, 0, 'BIF', 'No visa required for tourism'),
('MX', 'ET', 'visa_free', 90, 0, 'ETB', 'No visa required for tourism'),
('MX', 'ER', 'visa_free', 90, 0, 'ERN', 'No visa required for tourism'),
('MX', 'DJ', 'visa_free', 90, 0, 'DJF', 'No visa required for tourism'),
('MX', 'SO', 'visa_free', 30, 0, 'SOS', 'No visa required for tourism'),
('MX', 'SS', 'visa_free', 90, 0, 'SSP', 'No visa required for tourism'),
('MX', 'SD', 'visa_free', 90, 0, 'SDG', 'No visa required for tourism'),
('MX', 'EG', 'visa_free', 90, 0, 'EGP', 'No visa required for tourism'),
('MX', 'LY', 'visa_free', 90, 0, 'LYD', 'No visa required for tourism'),
('MX', 'TN', 'visa_free', 90, 0, 'TND', 'No visa required for tourism'),
('MX', 'DZ', 'visa_free', 90, 0, 'DZD', 'No visa required for tourism'),
('MX', 'MA', 'visa_free', 90, 0, 'MAD', 'No visa required for tourism'),
('MX', 'SN', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('MX', 'GN', 'visa_free', 90, 0, 'GNF', 'No visa required for tourism'),
('MX', 'SL', 'visa_free', 90, 0, 'SLL', 'No visa required for tourism'),
('MX', 'LR', 'visa_free', 90, 0, 'LRD', 'No visa required for tourism'),
('MX', 'CI', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('MX', 'GH', 'visa_free', 90, 0, 'GHS', 'No visa required for tourism'),
('MX', 'TG', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('MX', 'BJ', 'visa_free', 90, 0, 'XOF', 'No visa required for tourism'),
('MX', 'NG', 'visa_free', 90, 0, 'NGN', 'No visa required for tourism'),
('MX', 'CM', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('MX', 'TD', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('MX', 'CF', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('MX', 'CG', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('MX', 'CD', 'visa_free', 90, 0, 'CDF', 'No visa required for tourism'),
('MX', 'GA', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('MX', 'GQ', 'visa_free', 90, 0, 'XAF', 'No visa required for tourism'),
('MX', 'ST', 'visa_free', 90, 0, 'STN', 'No visa required for tourism'),
('MX', 'AO', 'visa_free', 90, 0, 'AOA', 'No visa required for tourism'),
('MX', 'MZ', 'visa_free', 90, 0, 'MZN', 'No visa required for tourism'),
('MX', 'MG', 'visa_free', 90, 0, 'MGA', 'No visa required for tourism'),
('MX', 'MU', 'visa_free', 90, 0, 'MUR', 'No visa required for tourism'),
('MX', 'SC', 'visa_free', 90, 0, 'SCR', 'No visa required for tourism'),
('MX', 'KM', 'visa_free', 90, 0, 'KMF', 'No visa required for tourism'),
('MX', 'YT', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),
('MX', 'RE', 'visa_free', 90, 0, 'EUR', 'No visa required for tourism'),

-- Middle East
('MX', 'IL', 'visa_free', 90, 0, 'ILS', 'No visa required for tourism'),
('MX', 'JO', 'visa_free', 90, 0, 'JOD', 'No visa required for tourism'),
('MX', 'LB', 'visa_free', 90, 0, 'LBP', 'No visa required for tourism'),
('MX', 'AE', 'visa_free', 90, 0, 'AED', 'No visa required for tourism'),
('MX', 'BH', 'visa_free', 90, 0, 'BHD', 'No visa required for tourism'),
('MX', 'KW', 'visa_free', 90, 0, 'KWD', 'No visa required for tourism'),
('MX', 'QA', 'visa_free', 90, 0, 'QAR', 'No visa required for tourism'),
('MX', 'OM', 'visa_free', 90, 0, 'OMR', 'No visa required for tourism'),
('MX', 'YE', 'visa_free', 90, 0, 'YER', 'No visa required for tourism'),

-- Countries requiring visas for Mexicans
('MX', 'IN', 'evisa', 60, 25, 'USD', 'Electronic visa required'),
('MX', 'PK', 'consulate_visa', 30, 60, 'USD', 'Visa must be obtained at consulate'),
('MX', 'BD', 'consulate_visa', 30, 50, 'USD', 'Visa must be obtained at consulate'),
('MX', 'LK', 'visa_on_arrival', 30, 35, 'USD', 'Visa on arrival available'),
('MX', 'NP', 'visa_on_arrival', 90, 30, 'USD', 'Visa on arrival available'),
('MX', 'MV', 'visa_on_arrival', 30, 0, 'USD', 'Visa on arrival available'),
('MX', 'TR', 'evisa', 90, 50, 'USD', 'Electronic visa required'),
('MX', 'GE', 'visa_free', 365, 0, 'GEL', 'No visa required for tourism'),
('MX', 'AM', 'visa_free', 180, 0, 'AMD', 'No visa required for tourism'),
('MX', 'AZ', 'visa_free', 30, 0, 'AZN', 'No visa required for tourism'),
('MX', 'KZ', 'visa_free', 30, 0, 'KZT', 'No visa required for tourism'),
('MX', 'KG', 'visa_free', 60, 0, 'KGS', 'No visa required for tourism'),
('MX', 'TJ', 'visa_free', 45, 0, 'TJS', 'No visa required for tourism'),
('MX', 'UZ', 'visa_free', 30, 0, 'UZS', 'No visa required for tourism'),
('MX', 'TM', 'visa_free', 30, 0, 'TMT', 'No visa required for tourism'),
('MX', 'AF', 'consulate_visa', 30, 80, 'USD', 'Visa must be obtained at consulate'),
('MX', 'IR', 'consulate_visa', 30, 80, 'USD', 'Visa must be obtained at consulate'),
('MX', 'IQ', 'consulate_visa', 30, 60, 'USD', 'Visa must be obtained at consulate'),
('MX', 'SY', 'consulate_visa', 30, 50, 'USD', 'Visa must be obtained at consulate'),
('MX', 'SA', 'consulate_visa', 90, 160, 'USD', 'Visa must be obtained at consulate')

ON CONFLICT (passport_country, destination_country) DO NOTHING; 