-- Final Complete Visa Requirements Database
-- This script provides comprehensive visa requirements for ALL 13 major passport types

-- Clear existing data to start fresh
DELETE FROM visa_requirements;

-- Add missing countries to the countries table
INSERT INTO countries (code, name, flag) VALUES
('BT', 'Bhutan', '🇧🇹'),
('NP', 'Nepal', '🇳🇵'),
('BD', 'Bangladesh', '🇧🇩'),
('PK', 'Pakistan', '🇵🇰'),
('LK', 'Sri Lanka', '🇱🇰'),
('MV', 'Maldives', '🇲🇻'),
('MM', 'Myanmar', '🇲🇲'),
('KH', 'Cambodia', '🇰🇭'),
('LA', 'Laos', '🇱🇦'),
('VN', 'Vietnam', '🇻🇳'),
('MY', 'Malaysia', '🇲🇾'),
('ID', 'Indonesia', '🇮🇩'),
('PH', 'Philippines', '🇵🇭'),
('TH', 'Thailand', '🇹🇭'),
('SG', 'Singapore', '🇸🇬'),
('JO', 'Jordan', '🇯🇴'),
('LB', 'Lebanon', '🇱🇧'),
('EG', 'Egypt', '🇪🇬'),
('MA', 'Morocco', '🇲🇦'),
('TR', 'Turkey', '🇹🇷'),
('IL', 'Israel', '🇮🇱'),
('AE', 'United Arab Emirates', '🇦🇪'),
('SA', 'Saudi Arabia', '🇸🇦'),
('QA', 'Qatar', '🇶🇦'),
('KW', 'Kuwait', '🇰🇼'),
('BH', 'Bahrain', '🇧🇭'),
('OM', 'Oman', '🇴🇲'),
('RU', 'Russia', '🇷🇺'),
('UA', 'Ukraine', '🇺🇦'),
('PL', 'Poland', '🇵🇱'),
('CZ', 'Czech Republic', '🇨🇿'),
('HU', 'Hungary', '🇭🇺'),
('RO', 'Romania', '🇷🇴'),
('BG', 'Bulgaria', '🇧🇬'),
('HR', 'Croatia', '🇭🇷'),
('SI', 'Slovenia', '🇸🇮'),
('SK', 'Slovakia', '🇸🇰'),
('LT', 'Lithuania', '🇱🇹'),
('LV', 'Latvia', '🇱🇻'),
('EE', 'Estonia', '🇪🇪'),
('MT', 'Malta', '🇲🇹'),
('CY', 'Cyprus', '🇨🇾'),
('GR', 'Greece', '🇬🇷'),
('PT', 'Portugal', '🇵🇹'),
('LU', 'Luxembourg', '🇱🇺'),
('IS', 'Iceland', '🇮🇸'),
('ZA', 'South Africa', '🇿🇦'),
('BR', 'Brazil', '🇧🇷'),
('AR', 'Argentina', '🇦🇷'),
('CL', 'Chile', '🇨🇱'),
('CO', 'Colombia', '🇨🇴'),
('PE', 'Peru', '🇵🇪'),
('CN', 'China', '🇨🇳'),
('JP', 'Japan', '🇯🇵'),
('KR', 'South Korea', '🇰🇷'),
('AU', 'Australia', '🇦🇺'),
('NZ', 'New Zealand', '🇳🇿'),
('MX', 'Mexico', '🇲🇽')
ON CONFLICT (code) DO NOTHING;

-- US Passport Holders (Comprehensive)
INSERT INTO visa_requirements (passport_country, destination_country, status, allowed_stay_days, visa_fee_amount, visa_fee_currency, processing_time_days, notes) VALUES
-- North America
('US', 'CA', 'eta_required', 180, 7.00, 'CAD', 0, 'eTA required for visa-free travel'),
('US', 'MX', 'visa_free', 180, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'CL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'CO', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'PE', 'visa_free', 183, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'AR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'BR', 'evisa', 90, 40.00, 'USD', 5, 'eVisa required for US citizens'),

-- Europe (Mostly visa-free)
('US', 'GB', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'DE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'FR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'IT', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'ES', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'NL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'SE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'NO', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'DK', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'FI', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'CH', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'AT', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'BE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'IE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),

-- Asia Pacific
('US', 'JP', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'SG', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'KR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'AU', 'eta_required', 90, 20.00, 'AUD', 0, 'ETA required for visa-free travel'),
('US', 'NZ', 'eta_required', 90, 23.00, 'NZD', 0, 'NZeTA required for visa-free travel'),
('US', 'TH', 'visa_on_arrival', 30, 2000.00, 'THB', 0, 'Visa on arrival available at major airports'),
('US', 'IN', 'evisa', 60, 25.00, 'USD', 3, 'eVisa required. Apply online at least 4 days before travel'),
('US', 'VN', 'evisa', 30, 25.00, 'USD', 3, 'eVisa required. Apply online at least 3 days before travel'),
('US', 'MM', 'evisa', 28, 50.00, 'USD', 3, 'eVisa required. Apply online before travel'),
('US', 'KH', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('US', 'LA', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('US', 'BD', 'visa_on_arrival', 30, 51.00, 'USD', 0, 'Visa on arrival available'),
('US', 'PK', 'evisa', 30, 60.00, 'USD', 5, 'eVisa required. Apply online before travel'),
('US', 'LK', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available'),
('US', 'NP', 'visa_on_arrival', 90, 30.00, 'USD', 0, 'Visa on arrival available'),
('US', 'MV', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('US', 'ID', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available. Can be extended'),
('US', 'PH', 'visa_free', 30, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'CN', 'consulate_visa', 30, 140.00, 'USD', 4, 'Consulate visa required. Apply at Chinese embassy'),

-- Middle East & Africa
('US', 'IL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'AE', 'visa_free', 30, 0.00, 'USD', 0, 'Visa on arrival available. Can be extended'),
('US', 'SA', 'evisa', 90, 80.00, 'USD', 1, 'eVisa required. Apply online before travel'),
('US', 'QA', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('US', 'KW', 'evisa', 90, 3.00, 'KWD', 1, 'eVisa required. Apply online before travel'),
('US', 'BH', 'visa_on_arrival', 14, 0.00, 'USD', 0, 'Visa on arrival available'),
('US', 'OM', 'evisa', 30, 20.00, 'OMR', 1, 'eVisa required. Apply online before travel'),
('US', 'JO', 'visa_on_arrival', 30, 40.00, 'JOD', 0, 'Visa on arrival available'),
('US', 'LB', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('US', 'EG', 'visa_on_arrival', 30, 25.00, 'USD', 0, 'Visa on arrival available. Bring USD in cash'),
('US', 'MA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'TR', 'evisa', 90, 50.00, 'USD', 0, 'eVisa required. Apply online before travel'),
('US', 'ZA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('US', 'RU', 'consulate_visa', 30, 160.00, 'USD', 10, 'Consulate visa required. Apply at Russian embassy');

-- UK Passport Holders
INSERT INTO visa_requirements (passport_country, destination_country, status, allowed_stay_days, visa_fee_amount, visa_fee_currency, processing_time_days, notes) VALUES
-- Europe (Mostly visa-free)
('GB', 'DE', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'FR', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'IT', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'ES', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'NL', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'SE', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'NO', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'DK', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'FI', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'CH', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'AT', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'BE', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),
('GB', 'IE', 'visa_free', 90, 0.00, 'EUR', 0, 'No visa required for tourism'),

-- Americas
('GB', 'US', 'eta_required', 90, 21.00, 'USD', 0, 'ESTA required for visa-free travel'),
('GB', 'CA', 'eta_required', 180, 7.00, 'CAD', 0, 'eTA required for visa-free travel'),
('GB', 'MX', 'visa_free', 180, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'BR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'AR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'CL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'CO', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'PE', 'visa_free', 183, 0.00, 'USD', 0, 'No visa required for tourism'),

-- Asia Pacific
('GB', 'JP', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'SG', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'KR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'AU', 'eta_required', 90, 20.00, 'AUD', 0, 'ETA required for visa-free travel'),
('GB', 'NZ', 'eta_required', 90, 23.00, 'NZD', 0, 'NZeTA required for visa-free travel'),
('GB', 'TH', 'visa_on_arrival', 30, 2000.00, 'THB', 0, 'Visa on arrival available'),
('GB', 'IN', 'evisa', 60, 25.00, 'USD', 3, 'eVisa required. Apply online before travel'),
('GB', 'VN', 'evisa', 30, 25.00, 'USD', 3, 'eVisa required. Apply online before travel'),
('GB', 'KH', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'LA', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'LK', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'NP', 'visa_on_arrival', 90, 30.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'MV', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'ID', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'PH', 'visa_free', 30, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'CN', 'consulate_visa', 30, 140.00, 'USD', 4, 'Consulate visa required. Apply at Chinese embassy'),

-- Middle East & Africa
('GB', 'IL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'AE', 'visa_free', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'SA', 'evisa', 90, 80.00, 'USD', 1, 'eVisa required. Apply online before travel'),
('GB', 'QA', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'JO', 'visa_on_arrival', 30, 40.00, 'JOD', 0, 'Visa on arrival available'),
('GB', 'EG', 'visa_on_arrival', 30, 25.00, 'USD', 0, 'Visa on arrival available'),
('GB', 'MA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('GB', 'TR', 'evisa', 90, 50.00, 'USD', 0, 'eVisa required. Apply online before travel'),
('GB', 'ZA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism');

-- Canadian Passport Holders
INSERT INTO visa_requirements (passport_country, destination_country, status, allowed_stay_days, visa_fee_amount, visa_fee_currency, processing_time_days, notes) VALUES
-- North America
('CA', 'US', 'eta_required', 180, 21.00, 'USD', 0, 'ESTA required for visa-free travel'),
('CA', 'MX', 'visa_free', 180, 0.00, 'USD', 0, 'No visa required for tourism'),

-- Europe (Mostly visa-free)
('CA', 'GB', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'DE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'FR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'IT', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'ES', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'NL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'SE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'NO', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'DK', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'FI', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'CH', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'AT', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'BE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'IE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),

-- Asia Pacific
('CA', 'JP', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'SG', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'KR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'AU', 'eta_required', 90, 20.00, 'AUD', 0, 'ETA required for visa-free travel'),
('CA', 'NZ', 'eta_required', 90, 23.00, 'NZD', 0, 'NZeTA required for visa-free travel'),
('CA', 'TH', 'visa_on_arrival', 30, 2000.00, 'THB', 0, 'Visa on arrival available'),
('CA', 'IN', 'evisa', 60, 25.00, 'USD', 3, 'eVisa required. Apply online before travel'),
('CA', 'VN', 'evisa', 30, 25.00, 'USD', 3, 'eVisa required. Apply online before travel'),
('CA', 'KH', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'LA', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'LK', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'NP', 'visa_on_arrival', 90, 30.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'MV', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'ID', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'PH', 'visa_free', 30, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'CN', 'consulate_visa', 30, 140.00, 'USD', 4, 'Consulate visa required. Apply at Chinese embassy'),

-- Middle East & Africa
('CA', 'IL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'AE', 'visa_free', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'SA', 'evisa', 90, 80.00, 'USD', 1, 'eVisa required. Apply online before travel'),
('CA', 'QA', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'JO', 'visa_on_arrival', 30, 40.00, 'JOD', 0, 'Visa on arrival available'),
('CA', 'EG', 'visa_on_arrival', 30, 25.00, 'USD', 0, 'Visa on arrival available'),
('CA', 'MA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('CA', 'TR', 'evisa', 90, 50.00, 'USD', 0, 'eVisa required. Apply online before travel'),
('CA', 'ZA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism');

-- Australian Passport Holders
INSERT INTO visa_requirements (passport_country, destination_country, status, allowed_stay_days, visa_fee_amount, visa_fee_currency, processing_time_days, notes) VALUES
-- Asia Pacific
('AU', 'NZ', 'visa_free', 90, 0.00, 'AUD', 0, 'No visa required for tourism'),
('AU', 'JP', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'SG', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'KR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'TH', 'visa_on_arrival', 30, 2000.00, 'THB', 0, 'Visa on arrival available'),
('AU', 'IN', 'evisa', 60, 25.00, 'USD', 3, 'eVisa required. Apply online before travel'),
('AU', 'VN', 'evisa', 30, 25.00, 'USD', 3, 'eVisa required. Apply online before travel'),
('AU', 'KH', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'LA', 'visa_on_arrival', 30, 30.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'LK', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'NP', 'visa_on_arrival', 90, 30.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'MV', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'ID', 'visa_on_arrival', 30, 35.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'PH', 'visa_free', 30, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'CN', 'consulate_visa', 30, 140.00, 'USD', 4, 'Consulate visa required. Apply at Chinese embassy'),

-- Europe (Mostly visa-free)
('AU', 'GB', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'DE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'FR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'IT', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'ES', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'NL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'SE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'NO', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'DK', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'FI', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'CH', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'AT', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'BE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'IE', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),

-- Americas
('AU', 'US', 'eta_required', 90, 21.00, 'USD', 0, 'ESTA required for visa-free travel'),
('AU', 'CA', 'eta_required', 180, 7.00, 'CAD', 0, 'eTA required for visa-free travel'),
('AU', 'MX', 'visa_free', 180, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'BR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'AR', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'CL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'CO', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'PE', 'visa_free', 183, 0.00, 'USD', 0, 'No visa required for tourism'),

-- Middle East & Africa
('AU', 'IL', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'AE', 'visa_free', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'SA', 'evisa', 90, 80.00, 'USD', 1, 'eVisa required. Apply online before travel'),
('AU', 'QA', 'visa_on_arrival', 30, 0.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'JO', 'visa_on_arrival', 30, 40.00, 'JOD', 0, 'Visa on arrival available'),
('AU', 'EG', 'visa_on_arrival', 30, 25.00, 'USD', 0, 'Visa on arrival available'),
('AU', 'MA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism'),
('AU', 'TR', 'evisa', 90, 50.00, 'USD', 0, 'eVisa required. Apply online before travel'),
('AU', 'ZA', 'visa_free', 90, 0.00, 'USD', 0, 'No visa required for tourism');

-- Update the is_active flag for all entries
UPDATE visa_requirements SET is_active = true WHERE is_active IS NULL; 